name: CI

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Tests
    needs: lint
    uses: ./.github/workflows/test.yml

  docker:
    name: Docker Build
    needs: test
    uses: ./.github/workflows/docker-build.yml
